shamefullyHoist: true

packages:
  - packages/*
  - simulator

catalog:
  "@antfu/eslint-config": ^4.13.0
  "@nuxt/devtools": ^2.4.0
  "@nuxt/icon": ^1.12.0
  "@nuxt/image": ^1.10.0
  "@pinia/nuxt": ^0.11.0
  "@primeuix/themes": ^1.1.1
  "@primevue/nuxt-module": ^4.3.4
  "@types/node": ^22.15.16
  "@unocss/nuxt": ^66.1.0
  "@vue/reactivity": ^3.5.13
  "@vueuse/core": ^13.1.0
  "@vueuse/nuxt": ^13.1.0
  "@zinkawaii/eslint-config": ^0.3.0
  "@zinkawaii/scripts": ^0.0.2
  "@zinkawaii/stylelint-config": ^0.3.1
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.1.0
  consola: ^3.4.2
  eslint: ^9.26.0
  nuxt: ^3.17.2
  pinia: ^3.0.2
  pinia-plugin-persistedstate: ^4.2.0
  primevue: ^4.3.4
  sass: ^1.87.0
  stylelint: ^16.19.1
  tsdown: ^0.11.1
  tsx: ^4.19.4
  undici: ^7.8.0
  unocss: ^66.1.0
  vue: ^3.5.13
  vue-draggable-plus: ^0.6.0
  vue-router: ^4.5.1
  vue-tsc: ^2.2.10

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
  - unrs-resolver
