shamefullyHoist: true

packages:
  - packages/*
  - simulator

catalog:
  "@antfu/eslint-config": ^4.13.2
  "@nuxt/devtools": ^2.4.1
  "@nuxt/icon": ^1.13.0
  "@nuxt/image": ^1.10.0
  "@pinia/nuxt": ^0.11.0
  "@primeuix/themes": ^1.1.1
  "@primevue/nuxt-module": ^4.3.4
  "@types/node": ^22.15.24
  "@unocss/nuxt": ^66.1.2
  "@vue/reactivity": ^3.5.16
  "@vueuse/core": ^13.3.0
  "@vueuse/nuxt": ^13.3.0
  "@zinkawaii/eslint-config": ^0.3.0
  "@zinkawaii/scripts": ^0.0.2
  "@zinkawaii/stylelint-config": ^0.3.1
  "@zinkawaii/tsconfig": ^0.0.2
  assemblyscript: 0.27.36
  bumpp: ^10.1.1
  consola: ^3.4.2
  eslint: ^9.27.0
  nuxt: ^3.17.4
  pinia: ^3.0.2
  pinia-plugin-persistedstate: ^4.3.0
  primevue: ^4.3.4
  sass: ^1.89.0
  stylelint: ^16.19.1
  tsdown: ^0.12.4
  tsx: ^4.19.4
  undici: ^7.10.0
  unocss: ^66.1.2
  vue: ^3.5.16
  vue-draggable-plus: ^0.6.0
  vue-router: ^4.5.1
  vue-tsc: ^2.2.10

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
  - unrs-resolver
