shamefullyHoist: true

packages:
  - packages/*
  - simulator

catalog:
  "@nuxt/devtools": ^3.1.1
  "@nuxt/icon": ^2.1.0
  "@nuxt/image": ^2.0.0
  "@pinia/nuxt": ^0.11.3
  "@primeuix/themes": ^2.0.1
  "@primevue/nuxt-module": ^4.5.0
  "@types/node": ^24.10.1
  "@unocss/nuxt": ^66.5.9
  "@vue/reactivity": ^3.5.25
  "@vueuse/core": ^14.1.0
  "@vueuse/nuxt": ^14.1.0
  "@zinkawaii/eslint-config": ^0.4.1
  "@zinkawaii/scripts": ^0.0.3
  "@zinkawaii/stylelint-config": ^0.3.4
  "@zinkawaii/tsconfig": ^0.0.2
  assemblyscript: 0.27.36
  bumpp: ^10.3.2
  consola: ^3.4.2
  eslint: ^9.39.1
  nuxt: ^4.2.1
  pinia: ^3.0.4
  pinia-plugin-persistedstate: ^4.7.1
  primevue: ^4.5.0
  sass: ^1.94.2
  stylelint: ^16.26.0
  tsdown: ^0.16.8
  tsx: ^4.20.6
  undici: ^7.16.0
  unocss: ^66.5.9
  vitest: ^4.0.14
  vue: ^3.5.25
  vue-draggable-plus: ^0.6.0
  vue-router: ^4.6.3
  vue-tsc: ^3.1.5

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
